apiVersion: v1
kind: Service
metadata:
  name: employer
spec:
  clusterIP: 10.0.0.252
  type: NodePort
  ports:
    - nodePort: 30180
      port: 8000
      targetPort: 8000
  selector:
    app: employer
