development:
  dialect: postgres
  database: business-card_development
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  port: 15432
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:mysecretpassword@127.0.0.1:15432/business-card_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:mysecretpassword@127.0.0.1:15432/business-card_production?sslmode=disable"}}