# global:
#   scrape_interval:     15s

scrape_configs:
  - job_name: 'self'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'web'
    scrape_interval: 5s
    static_configs:
      - targets: ['web:3000']
        labels:
          group: 'production'
